
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'MoreBtn': typeof import("../@core/components/MoreBtn.vue")['default']
    'ThemeSwitcher': typeof import("../@core/components/ThemeSwitcher.vue")['default']
    'CardStatisticsHorizontal': typeof import("../@core/components/cards/CardStatisticsHorizontal.vue")['default']
    'CardStatisticsVertical': typeof import("../@core/components/cards/CardStatisticsVertical.vue")['default']
    'CardStatisticsWithImages': typeof import("../@core/components/cards/CardStatisticsWithImages.vue")['default']
    'Checking': typeof import("../components/Checking.vue")['default']
    'DateRangePicker': typeof import("../components/DateRangePicker.vue")['default']
    'EightthStep1': typeof import("../components/EightthStep-1.vue")['default']
    'ErrorHeader': typeof import("../components/ErrorHeader.vue")['default']
    'FifthStep1': typeof import("../components/FifthStep-1.vue")['default']
    'FifthStep2': typeof import("../components/FifthStep-2.vue")['default']
    'FirstStep2': typeof import("../components/FirstStep-2.vue")['default']
    'FirstStep3': typeof import("../components/FirstStep-3.vue")['default']
    'FirstStep4': typeof import("../components/FirstStep-4.vue")['default']
    'FirstStep5': typeof import("../components/FirstStep-5.vue")['default']
    'FirstStep': typeof import("../components/FirstStep.vue")['default']
    'FourthStep1': typeof import("../components/FourthStep-1.vue")['default']
    'OtpInput': typeof import("../components/OtpInput.vue")['default']
    'SecondStep1': typeof import("../components/SecondStep-1.vue")['default']
    'SecondStep2': typeof import("../components/SecondStep-2.vue")['default']
    'SecondStep3': typeof import("../components/SecondStep-3.vue")['default']
    'SeventhStep1': typeof import("../components/SeventhStep-1.vue")['default']
    'SixthStep1': typeof import("../components/SixthStep-1.vue")['default']
    'ThirdStep1': typeof import("../components/ThirdStep-1.vue")['default']
    'ThirdStep2': typeof import("../components/ThirdStep-2.vue")['default']
    'ThirdStep3': typeof import("../components/ThirdStep-3.vue")['default']
    'ThirdStep4': typeof import("../components/ThirdStep-4.vue")['default']
    'UpgradeToPro': typeof import("../components/UpgradeToPro.vue")['default']
    'VueApexCharts': typeof import("../components/VueApexCharts.client.vue")['default']
    'Nn': typeof import("../components/nn.vue")['default']
    'NuxtWelcome': typeof import("../../../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../../../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../../../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtIsland': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../../../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Body']
    'VueApexCharts': IslandComponent<typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyMoreBtn': typeof import("../@core/components/MoreBtn.vue")['default']
    'LazyThemeSwitcher': typeof import("../@core/components/ThemeSwitcher.vue")['default']
    'LazyCardStatisticsHorizontal': typeof import("../@core/components/cards/CardStatisticsHorizontal.vue")['default']
    'LazyCardStatisticsVertical': typeof import("../@core/components/cards/CardStatisticsVertical.vue")['default']
    'LazyCardStatisticsWithImages': typeof import("../@core/components/cards/CardStatisticsWithImages.vue")['default']
    'LazyChecking': typeof import("../components/Checking.vue")['default']
    'LazyDateRangePicker': typeof import("../components/DateRangePicker.vue")['default']
    'LazyEightthStep1': typeof import("../components/EightthStep-1.vue")['default']
    'LazyErrorHeader': typeof import("../components/ErrorHeader.vue")['default']
    'LazyFifthStep1': typeof import("../components/FifthStep-1.vue")['default']
    'LazyFifthStep2': typeof import("../components/FifthStep-2.vue")['default']
    'LazyFirstStep2': typeof import("../components/FirstStep-2.vue")['default']
    'LazyFirstStep3': typeof import("../components/FirstStep-3.vue")['default']
    'LazyFirstStep4': typeof import("../components/FirstStep-4.vue")['default']
    'LazyFirstStep5': typeof import("../components/FirstStep-5.vue")['default']
    'LazyFirstStep': typeof import("../components/FirstStep.vue")['default']
    'LazyFourthStep1': typeof import("../components/FourthStep-1.vue")['default']
    'LazyOtpInput': typeof import("../components/OtpInput.vue")['default']
    'LazySecondStep1': typeof import("../components/SecondStep-1.vue")['default']
    'LazySecondStep2': typeof import("../components/SecondStep-2.vue")['default']
    'LazySecondStep3': typeof import("../components/SecondStep-3.vue")['default']
    'LazySeventhStep1': typeof import("../components/SeventhStep-1.vue")['default']
    'LazySixthStep1': typeof import("../components/SixthStep-1.vue")['default']
    'LazyThirdStep1': typeof import("../components/ThirdStep-1.vue")['default']
    'LazyThirdStep2': typeof import("../components/ThirdStep-2.vue")['default']
    'LazyThirdStep3': typeof import("../components/ThirdStep-3.vue")['default']
    'LazyThirdStep4': typeof import("../components/ThirdStep-4.vue")['default']
    'LazyUpgradeToPro': typeof import("../components/UpgradeToPro.vue")['default']
    'LazyVueApexCharts': typeof import("../components/VueApexCharts.client.vue")['default']
    'LazyNn': typeof import("../components/nn.vue")['default']
    'LazyNuxtWelcome': typeof import("../../../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../../../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../../../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtIsland': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../../../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyVueApexCharts': IslandComponent<typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const MoreBtn: typeof import("../@core/components/MoreBtn.vue")['default']
export const ThemeSwitcher: typeof import("../@core/components/ThemeSwitcher.vue")['default']
export const CardStatisticsHorizontal: typeof import("../@core/components/cards/CardStatisticsHorizontal.vue")['default']
export const CardStatisticsVertical: typeof import("../@core/components/cards/CardStatisticsVertical.vue")['default']
export const CardStatisticsWithImages: typeof import("../@core/components/cards/CardStatisticsWithImages.vue")['default']
export const Checking: typeof import("../components/Checking.vue")['default']
export const DateRangePicker: typeof import("../components/DateRangePicker.vue")['default']
export const EightthStep1: typeof import("../components/EightthStep-1.vue")['default']
export const ErrorHeader: typeof import("../components/ErrorHeader.vue")['default']
export const FifthStep1: typeof import("../components/FifthStep-1.vue")['default']
export const FifthStep2: typeof import("../components/FifthStep-2.vue")['default']
export const FirstStep2: typeof import("../components/FirstStep-2.vue")['default']
export const FirstStep3: typeof import("../components/FirstStep-3.vue")['default']
export const FirstStep4: typeof import("../components/FirstStep-4.vue")['default']
export const FirstStep5: typeof import("../components/FirstStep-5.vue")['default']
export const FirstStep: typeof import("../components/FirstStep.vue")['default']
export const FourthStep1: typeof import("../components/FourthStep-1.vue")['default']
export const OtpInput: typeof import("../components/OtpInput.vue")['default']
export const SecondStep1: typeof import("../components/SecondStep-1.vue")['default']
export const SecondStep2: typeof import("../components/SecondStep-2.vue")['default']
export const SecondStep3: typeof import("../components/SecondStep-3.vue")['default']
export const SeventhStep1: typeof import("../components/SeventhStep-1.vue")['default']
export const SixthStep1: typeof import("../components/SixthStep-1.vue")['default']
export const ThirdStep1: typeof import("../components/ThirdStep-1.vue")['default']
export const ThirdStep2: typeof import("../components/ThirdStep-2.vue")['default']
export const ThirdStep3: typeof import("../components/ThirdStep-3.vue")['default']
export const ThirdStep4: typeof import("../components/ThirdStep-4.vue")['default']
export const UpgradeToPro: typeof import("../components/UpgradeToPro.vue")['default']
export const VueApexCharts: typeof import("../components/VueApexCharts.client.vue")['default']
export const Nn: typeof import("../components/nn.vue")['default']
export const NuxtWelcome: typeof import("../../../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../../../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtIsland: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../../../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Body']
export const VueApexCharts: IslandComponent<typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyMoreBtn: typeof import("../@core/components/MoreBtn.vue")['default']
export const LazyThemeSwitcher: typeof import("../@core/components/ThemeSwitcher.vue")['default']
export const LazyCardStatisticsHorizontal: typeof import("../@core/components/cards/CardStatisticsHorizontal.vue")['default']
export const LazyCardStatisticsVertical: typeof import("../@core/components/cards/CardStatisticsVertical.vue")['default']
export const LazyCardStatisticsWithImages: typeof import("../@core/components/cards/CardStatisticsWithImages.vue")['default']
export const LazyChecking: typeof import("../components/Checking.vue")['default']
export const LazyDateRangePicker: typeof import("../components/DateRangePicker.vue")['default']
export const LazyEightthStep1: typeof import("../components/EightthStep-1.vue")['default']
export const LazyErrorHeader: typeof import("../components/ErrorHeader.vue")['default']
export const LazyFifthStep1: typeof import("../components/FifthStep-1.vue")['default']
export const LazyFifthStep2: typeof import("../components/FifthStep-2.vue")['default']
export const LazyFirstStep2: typeof import("../components/FirstStep-2.vue")['default']
export const LazyFirstStep3: typeof import("../components/FirstStep-3.vue")['default']
export const LazyFirstStep4: typeof import("../components/FirstStep-4.vue")['default']
export const LazyFirstStep5: typeof import("../components/FirstStep-5.vue")['default']
export const LazyFirstStep: typeof import("../components/FirstStep.vue")['default']
export const LazyFourthStep1: typeof import("../components/FourthStep-1.vue")['default']
export const LazyOtpInput: typeof import("../components/OtpInput.vue")['default']
export const LazySecondStep1: typeof import("../components/SecondStep-1.vue")['default']
export const LazySecondStep2: typeof import("../components/SecondStep-2.vue")['default']
export const LazySecondStep3: typeof import("../components/SecondStep-3.vue")['default']
export const LazySeventhStep1: typeof import("../components/SeventhStep-1.vue")['default']
export const LazySixthStep1: typeof import("../components/SixthStep-1.vue")['default']
export const LazyThirdStep1: typeof import("../components/ThirdStep-1.vue")['default']
export const LazyThirdStep2: typeof import("../components/ThirdStep-2.vue")['default']
export const LazyThirdStep3: typeof import("../components/ThirdStep-3.vue")['default']
export const LazyThirdStep4: typeof import("../components/ThirdStep-4.vue")['default']
export const LazyUpgradeToPro: typeof import("../components/UpgradeToPro.vue")['default']
export const LazyVueApexCharts: typeof import("../components/VueApexCharts.client.vue")['default']
export const LazyNn: typeof import("../components/nn.vue")['default']
export const LazyNuxtWelcome: typeof import("../../../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../../../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../../../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtIsland: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../../../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyVueApexCharts: IslandComponent<typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
