// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/11/2024, 12:38:01 PM
const configMerger = require("C:/Users/HASEE/Desktop/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/HASEE/Desktop/testingforfv/vue-form/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HASEE/Desktop/testingforfv/vue-form/@core/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HASEE/Desktop/testingforfv/vue-form/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HASEE/Desktop/testingforfv/vue-form/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HASEE/Desktop/testingforfv/vue-form/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HASEE/Desktop/testingforfv/vue-form/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HASEE/Desktop/testingforfv/vue-form/plugins/**/*.{js,ts,mjs}","C:/Users/HASEE/Desktop/testingforfv/vue-form/@core/utils/**/*.{js,ts,mjs}","C:/Users/HASEE/Desktop/testingforfv/vue-form/@core/composable/**/*.{js,ts,mjs}","C:/Users/HASEE/Desktop/testingforfv/vue-form/plugins/*/composables/*/**/*.{js,ts,mjs}","C:/Users/HASEE/Desktop/testingforfv/vue-form/stores/**/*.{js,ts,mjs}","C:/Users/HASEE/Desktop/testingforfv/vue-form/composables/**/*.{js,ts,mjs}","C:/Users/HASEE/Desktop/testingforfv/vue-form/utils/**/*.{js,ts,mjs}","C:/Users/HASEE/Desktop/testingforfv/vue-form/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HASEE/Desktop/testingforfv/vue-form/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/HASEE/Desktop/testingforfv/vue-form/app.config.{js,ts,mjs}"] }));

module.exports = config
